language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer --dev --prefer-source install

notifications:
    webhooks: http://sonata-project.org/bundles/notification/master/travis
    
matrix:
  allow_failures:
    - php: hhvm
